### ISSUE TITLE
How to remove the certificate?

### ISSUE THREAD

**Issue by eshate** [Mobile-IoT-Security-Lab/HideDroid#9]
How to remove the certificate?

**Comment by Dado1513** [comment]
Hi @eshate ,
Regarding your previous issue, HideDroid in order to work decompile, inject their certificate, and then recompile the selected app in order to be able to intercept and anonymize data.
So the dir that you find is because you have tried to anonymize data belonging to the Opera app.

Regarding the second question, is simple: https://www.technipages.com/how-to-remove-all-stored-certificates-on-android.

**Comment by eshate** [comment]
Okay, sorry for the sound of my previous post. 
But I just found it quite strange, maybe you can help me (even if issue closed). **How it's possible that I was trying to anonymize data belonging to the Opera app if I never installed (or try to, or even think of) an Opera app?** That's why I was like WTF.
